### ISSUE TITLE
Calculation of local_offset is incorrect

### ISSUE THREAD

**Issue by peterhinch** [inmcm/micropyGPS#16]
In [this line](https://github.com/inmcm/micropyGPS/blob/e1b69fded7a79605fb61b3b395644ff4e52876e0/micropyGPS.py#L185) (which occurs three times in the code) the hours value should be reduced modulo 24 to avoid illegal values.

**Comment by inmcm** [comment]
Fixed in https://github.com/inmcm/micropyGPS/commit/4c226e96bf98fb6600956ce32fef0444cc780f45
