### ISSUE TITLE
date_string long format shows incorrect suffix on 23rd of month

### ISSUE THREAD

**Issue by peterhinch** [inmcm/micropyGPS#17]
[this line](https://github.com/inmcm/micropyGPS/blob/c30df5828df493e5391b17dfc36a80fe5dfd955b/micropyGPS.py#L766) should read:
```python
elif self.date[0] in (3, 23):
```

**Comment by inmcm** [comment]
Thanks! Fixed in e3f849b12c5e11bf0e8d88c2dc995ffe20295333
