### ISSUE TITLE
Lypo import issues

### ISSUE THREAD

**Issue by nikolaymomchev** [inmcm/micropyGPS#2]
Whenever I try to import micropyGPS no further part of the main.py code executes. Prints put inside micropyGPS don't execute either. This fork of Mycropython doesn't have pyb. Can that be a problem?

**Comment by inmcm** [comment]
Please post the problem code as a gist. I'm not familiar with the Lypo platform; do you mean LoPy? micropyGPS doesn't depend on the pyb interface of the standard micropython, I just use it in the the examples. You're have to adapt those example to the serial interface of your platform. If you're using LoPy, or any pycom product, maybe start by looking here: 
https://docs.pycom.io/pycom_esp32/library/machine.UART.html

**Comment by ralphPY** [comment]
Hi, I had the same problem on LoPy with Pytrack. After removing the the part starting with 
if __name__ == "__main__":
micropyGPS imports just fine.

I'm quite new to this myself, so not exactly sure why, but learning every day ;-)

**Comment by inmcm** [comment]
It sounds like the what you're trying to do is

`if __name__ == '__main__':`

which has namespace significance in Python

https://stackoverflow.com/questions/419163/what-does-if-name-main-do
