### ISSUE TITLE
date value from RMC string not stored like timestamp

### ISSUE THREAD

**Issue by mmedvedmtd** [inmcm/micropyGPS#21]
Our adafruit Ultimate GPS has an RTC w/ clock backup, and we noticed that when we were getting RMC strings w/no fix, time would be correct, but the date would be wrong.
`
else: # Clear   Position Data if Sentence is 'Invalid' 
 self._latitude = (0, 0.0, 'N')
 self._longitude = (0, 0.0, 'W')
 self.speed = (0.0, 0.0, 0.0)
 self.course = 0.0
 self.date = (0, 0, 0)
 self.valid = False
`
Notice that self.date = 0, but timestamp is left alone.  I realize this probably is the opposite of the previous issue's intent, but it seems to me in the case of an RTC enabled GPS, both date and time should come through if the GPS has them stored.

**Comment by inmcm** [comment]
Fixed in #23
