### ISSUE TITLE
my_gps.update() always returns None for RMC messages

### ISSUE THREAD

**Issue by jaredw42** [inmcm/micropyGPS#25]
Hello

When using micropyGPS to parse NMEA messages in a file, I noticed that the my_gps.update() method always returns 'None', for RMC messages, even if the sentence has been parsed. The RMC messages  are valid and are counted as "clean sentences" by the statistics parser.

I have tried a number of files with different receiver types, with consistent results.

Thanks for making a great tool. Other than this, I have had no issues and this was exactly what i was looking for in a NMEA parser.

**Comment by inmcm** [comment]
Can you try running the pytest test suite on your host you're having issues (`pytest -xvvv test_micropyGPS.py`) and post the results? If that works, can you post some the strings you're having issues with?

**Comment by jaredw42** [comment]
Pytest seems happy on my machine 

    ➜  micropyGPS git:(master) pytest -xvvv test_micropyGPS.py
    ============================== test session starts                ===============================
    platform darwin -- Python 3.7.1, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- 
    /usr/local/opt/python/bin/python3.7
    cachedir: .pytest_cache
    rootdir: /Users/jwilson/SwiftNav/micropyGPS, inifile:
    collected 9 items

    test_micropyGPS.py::test_rmc_sentences PASSED                              [ 11%]
    test_micropyGPS.py::test_vtg_sentences PASSED                              [ 22%]
    test_micropyGPS.py::test_gga_sentences PASSED                              [ 33%]
    test_micropyGPS.py::test_gsa_sentences PASSED                              [ 44%]
    test_micropyGPS.py::test_gsv_sentences PASSED                              [ 55%]
    test_micropyGPS.py::test_gll_sentences PASSED                              [ 66%]
    test_micropyGPS.py::test_logging PASSED                                    [ 77%]
    test_micropyGPS.py::test_pretty_print PASSED                               [ 88%]
    test_micropyGPS.py::test_coordinate_representations PASSED                 [100%]

    ============================ 9 passed in 0.12 seconds ============================

Here's a short example of a NMEA log im having issue with.
[nmea_out.txt](https://github.com/inmcm/micropyGPS/files/2646900/nmea_out.txt)

**Comment by inmcm** [comment]
The RMC sentences lack course data; same problem as #9 
Fixed in f67aeb93bbc09bd3f15aa24cfa43a0ab41565b25
