### ISSUE TITLE
Unhandled exception occured

### ISSUE THREAD

**Issue by ttadam** [inmcm/micropyGPS#26]
Unhandled exception in thread started by <bound_method>
Traceback (most recent call last):
  File "/flash/lib/L76micropyGPS.py", line 60, in feedMicroGPS
  File "/flash/lib/micropyGPS.py", line 615, in update
  File "/flash/lib/micropyGPS.py", line 372, in gpgga
  File "/flash/lib/micropyGPS.py", line 363, in gpgga
IndexError: list index out of range
I created the object from repl, it was working fine.
Then I left the computer, and this is what I saw.

**Comment by gregcope** [comment]
Hi. I think this might be a problem in L76micropyGPS.py

Do you have a copy of the Sentence that made it fail?

**Comment by ttadam** [comment]
Sorry but no. I just used it from the REPL for something quick.

**Comment by inmcm** [comment]
What commit of `micropyGPS.py` and GPS receiver were you using? It looks like  a truncated, but valid, GPGGA sentence was received.

**Comment by adamticz** [comment]
I am not much of a help, sorry. 
I have no idea, I just copy pasted the full code into a new .py file a 1 or 2 month ago. I checked the code, maybe there is an identifier for the version but i didn't find anythink

**Comment by inmcm** [comment]
I add some extra error IndexError handling and some general GGA parser improvements in 70bd71b32fbbbc22e6f3bf85a4116edcea478766 
Hope that solves the issue.
