### ISSUE TITLE
Decimal latitude and longitude

### ISSUE THREAD

**Issue by hickford** [inmcm/micropyGPS#3]
Hi. Can the library give me the latitude and longitude in decimal? I'd find this easier to work with. For example the [statue of liberty](https://tools.wmflabs.org/geohack/geohack.php?pagename=Statue_of_Liberty&params=40_41_21_N_74_2_40_W_region:US-NY_type:landmark_scale:5000) would be at `40.689167, -74.044444`

**Comment by inmcm** [comment]
Feature added in https://github.com/inmcm/micropyGPS/commit/af8a645a071b1b6e03bd22ac3b9e6f1d38b7a403

used the coord_format parameter to set your lat/long formatting 

```python
> f = MicropyGPS()
> f.coord_format = 'dd'
# ....process some sentences
> f.latitude
   [40.446, N]
> f.latitude_string()
   40.446° N
```
