### ISSUE TITLE
Out of Memory Issue

### ISSUE THREAD

**Issue by markserrano915** [inmcm/micropyGPS#6]
I'm a getting an Out of Memory Error whenever I import micropyGPS on a NodeMcu v2 board with Micropython 1.9.1 (see https://www.amazon.com/HiLetgo-Version-NodeMCU-Internet-Development/dp/B010O1G1ES).

Based on your project's descrioption, you are using a Pyboard which has 192KiB RAM while the NodeMcu board has 128KiB RAM. Even with a simple import with no classes at all, I still get the Out of Memory Error. I am surprised the extra 64KiB makes a big difference in loading this library.

I am wondering if you were able to load your library on a NodeMcu board previously. I'm planning to strip out the library to the bare essentials (based on my needs), but before that I was thinking if you've done prior testing with a NodeMcu before. Or if you can provide a quick tip on which ones I can strip out quickly.

I will forego any error checking to save memory and assume happy path. All I want is read the coordinates from my Adafruit GPS device. Once that's read, send it to Raspberry for further processing. I am thinking of porting your implementation to Raspberry (if it doesn't exist yet).

I think by the time you read this, I would already start hacking your code tonight or tomorrow.

**Comment by markserrano915** [comment]
Yes, I can just use my Raspberry directly and interface my GPS module with it, but I have my reasons why I want the NodeMcu as the point of data capture (for example it's smaller and cheaper).

**Comment by inmcm** [comment]
I did some experiments with the ```mem_info``` within the Unix version of micro python to see just how much memory was being consumed on import:

```
>>> from micropython import mem_info
>>> mem_info()
mem: total=6681, current=2911, peak=4486
stack: 928 out of 80000
GC: total: 2072832, used: 4096, free: 2068736
 No. of 1-blocks: 41, 2-blocks: 21, max blk sz: 41, max free sz: 64640
>>> from micropyGPS import MicropyGPS
>>> mem_info()
mem: total=107812, current=29518, peak=92472
stack: 928 out of 80000
GC: total: 2072832, used: 33824, free: 2039008
 No. of 1-blocks: 300, 2-blocks: 45, max blk sz: 80, max free sz: 61718
```
As a quick test, I deleted all the "test" at in the ```__main__``` section and re-ran the import test. Surprisingly, the usage was much lower
```
>>> from micropython import mem_info
>>> mem_info()
mem: total=8610, current=2980, peak=4555
stack: 928 out of 80000
GC: total: 2072832, used: 4000, free: 2068832
 No. of 1-blocks: 46, 2-blocks: 17, max blk sz: 41, max free sz: 64643
>>> from micropyGPS import MicropyGPS
>>> mem_info()
mem: total=87457, current=22271, peak=70409
stack: 928 out of 80000
GC: total: 2072832, used: 25280, free: 2047552
 No. of 1-blocks: 196, 2-blocks: 30, max blk sz: 80, max free sz: 62461
```

I re-ran the test several times and got similar numbers. I went ahead and stripped the the code from ```__main__``` and pushed it into a separate tests.py. It's very interesting that just importing the class brings in all that other code from the main module. Maybe a bug in Micropython?

**Comment by ckuethe** [comment]
I can reproduce this. I need to think about how to reduce memory use even more (possibly precompiling to frozen bytecode) because I'm also running a bunch of other i2c devices on the same nodemcu.

**Comment by ckuethe** [comment]
Also, the nodemcu board might have 128kB RAM, but less than 50kB are available once the underlying RTOS and micropython are load.

**Comment by capedra** [comment]
@markserrano915 @inmcm @ckuethe 
I've been trying to use this library on Wemos D1 Mini Lite 1.0.0.
Here it is the output:
```
>>> from micropython import mem_info
>>> mem_info()
stack: 2096 out of 8192
GC: total: 35968, used: 10240, free: **25728**
 No. of 1-blocks: 26, 2-blocks: 4, max blk sz: 264, max free sz: 554
>from micropyGPS import MicropyGPS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 832 bytes
```

**Comment by tcinbis** [comment]
I could use the library on an ESP32 after precompiling it as a frozen module.
