### ISSUE TITLE
l76 glonass support

### ISSUE THREAD

**Issue by ozeta** [inmcm/micropyGPS#7]
Hi, i'm using this library on my wipy + pytrack shield.

it uses the quectel l76 gps + glonass receiver. here the spec: http://ecksteinimg.de/Datasheet/QuectelL76-LGNSS.pdf

i see that glonass specific sentences are: GLGSV, GNGLL, GNGSA, that are not implemented in your code. You think you will add those features? If I have some spare time i'd like to contribute.

from the spec file, i see that the only difference between:

[gp|gn] rmc
[gp|gl] gsv
[gp|gn] gll
[gp|gn] gsa

is only the "name". as the nmea sentence has the same format. so i think they can be added into 
 `   supported_sentences` without new parsers.

however, as I understand from the notes in 2.1 chapter in the spec file, gp-gll uses only gps satellites and gn-gll uses gps + glonass satellites. so during parsing, gngll sentence should have some sort of priority on gpgll.

what do you think? 

:D

**Comment by ozeta** [comment]
update: i tried updating `supported_sentences`, trivially appending some items to the dict

```
    supported_sentences = {'GPRMC': gprmc, 'GPGGA': gpgga, 'GPVTG': gpvtg, 'GPGSA': gpgsa,
                           'GPGSV': gpgsv, 'GPGLL': gpgll}
    supported_sentences['GNRMC'] = gprmc
    supported_sentences['GLGSV'] = gpgsv
    supported_sentences['GNGLL'] = gpgll
    supported_sentences['GNGSA'] = gpgsa
```

when Pytrack's L76 fixes the position, the uart port doesnt print GPGLL and GPGSA sentence but only GNGLL and GNGSA sentences and gps.update(sentence) returns None.

After my update, it correctly returns both 'GNGLL' or 'GNGSA' and it can use the NMEA data

**Comment by gregcope** [comment]
@inmcm Is there a reason not to include the Pytrack L76 sentences in the ```support_sentences```?

Something like;

```
    supported_sentences = {'GPRMC': gprmc, 'GLRMC': gprmc, 'GNRMC': gprmc,
                           'GPGGA': gpgga, 'GLGGA': gpgga,
                           'GPVTG': gpvtg, 'GLVTG': gpvtg,
                           'GPGSA': gpgsa, 'GLGSA': gpgsa, 'GNGSA': gpgsa,
                           'GPGSV': gpgsv, 'GLGSV': gpgsv,
                           'GPGLL': gpgll, 'GLGLL': gpgll, 'GNGLL': gpgll,
                          }
```
