### ISSUE TITLE
gprmc parsing problem

### ISSUE THREAD

**Issue by kanalizator** [inmcm/micropyGPS#9]
Hello, thanks for micropyGPS.
I am testing it right now. Unfortunately, there is a problem with parsing GPRMC sentance for my GPS module.
Example sentance:
`$GPRMC,165904.00,A,xxxx.85300,N,yyyyy.85129,E,0.564,,011217,,,A*77`
gps_segments (from PyCharm debugger):
```
gps_segments = {list} <class 'list'>: ['GPRMC', '165904.00', 'A', 'xxxx.85300', 'N', 'yyyyy.85129', 'E', '0.564', '', '011217', '', '', 'A', '77']
 00 = {str} 'GPRMC'
 01 = {str} '165904.00'
 02 = {str} 'A'
 03 = {str} 'xxxx.85300'
 04 = {str} 'N'
 05 = {str} 'yyyyy.85129'
 06 = {str} 'E'
 07 = {str} '0.564'
 08 = {str} ''
 09 = {str} '011217'
 10 = {str} ''
 11 = {str} ''
 12 = {str} 'A'
 13 = {str} '77'
 __len__ = {int} 14
```
Within function **gprmc** there is a code:
```
# Course
try:
    course = float(self.gps_segments[8])
except ValueError:
    return False
```
Since there is no Course data the parsing fails traying to do _course = float(str)_
```
Traceback (most recent call last):
  File "xxx", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
ValueError: could not convert string to float: 
```
I just wanted to let you know.
But still its a great SW and the fix is simple.

**Comment by inmcm** [comment]
Fixed in f67aeb93bbc09bd3f15aa24cfa43a0ab41565b25
